#  _                _              A plugin by Xpoxy.
# | |              | |             https://lockermod.github.io
# | |     ___   ___| | _____ _ __ 
# | |    / _ \ / __| |/ / _ \ '__|
# | |___| (_) | (__|   <  __/ |   
# |______\___/ \___|_|\_\___|_|    https://github.com/spigbop/Locker

# Lines starting with # are comments.

# There are two save types: 'localfiles' or 'mysql'
file-save-type: localfiles

auto-saver:
  # Locker saves data before the server shuts down. But will need a proper shutdown and
  # if your server crashes it probably wont save! Enable auto saver to backup your data.
  enable: false
  # Time between each save in seconds
  interval: 3600
  # Wheather or not to send console messages after auto saving.
  console-send-message: true

# Only used if 'file-save-type' is 'localfiles'
localfiles-savepath: ..\Database\
# You can save anywhere you like, make sure file permissions allow it. '..' automatically
# finds the locker folder. Use forward slashes '/' for OSX operating systems.

# Only used if 'file-save-type' is 'mysql'
mysql-connection:
  server-ip: 127.0.0.1
  username-id: root
  port: 3306
  password: 3306
  database-name: locker-unturned
  # Supported charsets: https://dev.mysql.com/doc/refman/8.0/en/charset-charsets.html
  charset: utf8mb4
